```python
print('Hello World!')
```

In [2]:
import pandas as pd
df = pd.read_csv('laptops.csv')
df

     brand             model  ram hd_type  hd_size  ...  graphic_card_brand  graphic_card_size       os weight  comments
0     Dell  Inspiron 15-3567    4     hdd     1024  ...               intel                NaN    linux   2.50       NaN
1    Apple       MacBook Air    8     ssd      128  ...               intel                2.0      mac   1.35       NaN
2    Apple       MacBook Air    8     ssd      256  ...               intel                2.0      mac   1.35       NaN
3    Apple       MacBook Pro    8     ssd      128  ...               intel                2.0      mac   3.02       NaN
4    Apple       MacBook Pro    8     ssd      256  ...               intel                2.0      mac   3.02       NaN
..     ...               ...  ...     ...      ...  ...                 ...                ...      ...    ...       ...
162   Asus            A555LF    8     hdd     1024  ...              nvidia                2.0  windows   2.30       NaN
163   Asus     X555LA-XX172D    4     hdd      500  ...               intel                NaN    linux   2.30       NaN
164   Asus            X554LD    2     hdd      500  ...               intel                1.0    linux   2.30       NaN
165   Asus    X550LAV-XX771D    2     hdd      500  ...               intel                NaN    linux   2.50       NaN
166   Asus     X540LA-XX538T    4     hdd     1024  ...               intel                NaN  windows   2.30       NaN

[167 rows x 15 columns]

In [3]:
df.head()

   brand             model  ram hd_type  hd_size  ...  graphic_card_brand  graphic_card_size     os weight  comments
0   Dell  Inspiron 15-3567    4     hdd     1024  ...               intel                NaN  linux   2.50       NaN
1  Apple       MacBook Air    8     ssd      128  ...               intel                2.0    mac   1.35       NaN
2  Apple       MacBook Air    8     ssd      256  ...               intel                2.0    mac   1.35       NaN
3  Apple       MacBook Pro    8     ssd      128  ...               intel                2.0    mac   3.02       NaN
4  Apple       MacBook Pro    8     ssd      256  ...               intel                2.0    mac   3.02       NaN

[5 rows x 15 columns]

In [4]:
df.head(10)

   brand                   model  ram hd_type  ...  graphic_card_size     os  weight             comments
0   Dell        Inspiron 15-3567    4     hdd  ...                NaN  linux    2.50                  NaN
1  Apple             MacBook Air    8     ssd  ...                2.0    mac    1.35                  NaN
2  Apple             MacBook Air    8     ssd  ...                2.0    mac    1.35                  NaN
3  Apple             MacBook Pro    8     ssd  ...                2.0    mac    3.02                  NaN
4  Apple             MacBook Pro    8     ssd  ...                2.0    mac    3.02                  NaN
5  Apple  MacBook Pro (TouchBar)   16     ssd  ...                2.0    mac    2.50                  NaN
6  Apple  MacBook Pro (TouchBar)   16     ssd  ...                2.0    mac    1.37                  NaN
7  Apple                MacBook     8     ssd  ...                2.0    mac    0.92                  NaN
8   Dell             Vostro 3468    4     hdd  ...                NaN  linux    1.76  Integrated Graphics
9   Dell      Inspiron 15.6 3552    4     hdd  ...                NaN  linux    2.19  Integrated Graphics

[10 rows x 15 columns]

In [5]:
df.tail()

    brand           model  ram hd_type  hd_size  ...  graphic_card_brand  graphic_card_size       os weight  comments
162  Asus          A555LF    8     hdd     1024  ...              nvidia                2.0  windows    2.3       NaN
163  Asus   X555LA-XX172D    4     hdd      500  ...               intel                NaN    linux    2.3       NaN
164  Asus          X554LD    2     hdd      500  ...               intel                1.0    linux    2.3       NaN
165  Asus  X550LAV-XX771D    2     hdd      500  ...               intel                NaN    linux    2.5       NaN
166  Asus   X540LA-XX538T    4     hdd     1024  ...               intel                NaN  windows    2.3       NaN

[5 rows x 15 columns]

In [6]:
df.tail(10)

      brand                          model  ram  ...       os  weight                                      comments
157  Lenovo  IdeaPad 520-15IKB 80YL00RXIN     8  ...  windows    2.20  Core i7-7500U 7th Gen processor, Dolby Audio
158    Asus                  X540YA-XO290D    4  ...    linux    2.00                                           NaN
159    Asus                        P2420SA    4  ...    linux    1.95                                           NaN
160    Asus                  X540LA-XX596D    4  ...    linux    1.90                                           NaN
161    Asus                 X541UA-GO1345D    4  ...    linux    1.84                                           NaN
162    Asus                         A555LF    8  ...  windows    2.30                                           NaN
163    Asus                  X555LA-XX172D    4  ...    linux    2.30                                           NaN
164    Asus                         X554LD    2  ...    linux    2.30                                           NaN
165    Asus                 X550LAV-XX771D    2  ...    linux    2.50                                           NaN
166    Asus                  X540LA-XX538T    4  ...  windows    2.30                                           NaN

[10 rows x 15 columns]

In [7]:
df.shape

(167, 15)

In [8]:
df.shape[0]

167

In [9]:
df.shape[1]

15

In [10]:
df.index

RangeIndex(start=0, stop=167, step=1)

In [11]:
df.columns

Index(['brand', 'model', 'ram', 'hd_type', 'hd_size', 'screen_size', 'price',
       'processor_brand', 'processor_model', 'clock_speed',
       'graphic_card_brand', 'graphic_card_size', 'os', 'weight', 'comments'],
      dtype='object')

In [12]:
df.columns[0]

'brand'

In [13]:
df.columns[1]

'model'

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167 entries, 0 to 166
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   brand               167 non-null    object
 1   model               167 non-null    object
 2   ram                 167 non-null    int64
 3   hd_type             167 non-null    object
 4   hd_size             167 non-null    int64
 5   screen_size         167 non-null    float64
 6   price               167 non-null    int64
 7   processor_brand     167 non-null    object
 8   processor_model     167 non-null    object
 9   clock_speed         166 non-null    float64
 10  graphic_card_brand  163 non-null    object
 11  graphic_card_size   81 non-null     float64
 12  os                  167 non-null    object
 13  weight              160 non-null    float64
 14  comments            55 non-null     object
dtypes: float64(4), int64(3), object(8)
memory usage: 19.7+ KB

In [15]:
df.describe()

              ram     hd_size  screen_size          price  clock_speed  graphic_card_size      weight
count  167.000000   167.00000   167.000000     167.000000   166.000000          81.000000  160.000000
mean     6.898204   768.91018    14.775210   64132.898204     2.321084          52.160494    2.250813
std      3.787479   392.99080     1.376526   42797.674010     0.554187         444.134142    0.648446
min      2.000000    32.00000    10.100000   13872.000000     1.100000           1.000000    0.780000
25%      4.000000   500.00000    14.000000   35457.500000     1.900000           2.000000    1.900000
50%      8.000000  1024.00000    15.600000   47990.000000     2.300000           2.000000    2.200000
75%      8.000000  1024.00000    15.600000   77494.500000     2.600000           4.000000    2.600000
max     16.000000  2048.00000    17.600000  226000.000000     3.800000        4000.000000    4.200000

In [16]:
df.sort_values(by='price')

         brand                       model  ram  ...       os  weight                                           comments
148       Acer             Aspire SW3-016     2  ...  windows     1.2                                                NaN
83        Acer     A315-31CDC UN.GNTSI.001    2  ...  windows     2.1                                                NaN
108       Acer  Aspire ES-15 NX.GKYSI.010     4  ...  windows     2.4                                                NaN
100       Acer    A315-31-P4CRUN.GNTSI.002    4  ...  windows     NaN                                                NaN
73        Acer             Aspire ES1-523     4  ...    linux     2.4                                                NaN
..         ...                         ...  ...  ...      ...     ...                                                ...
154  Microsoft      Surface Book CR9-00013    8  ...  windows     1.5                                                NaN
31        Acer                 Predator 17   16  ...  windows     4.2                                Integrated Graphics
96   Alienware          AW13R3-7000SLV-PUS    8  ...  windows     2.6  13.3 inch FHD (1920 x 1080) IPS Anti-Glare 300...
90   Alienware                 15 Notebook   16  ...  windows     3.5     Maximum Display Resolution : 1920 x 1080 pixel
5        Apple      MacBook Pro (TouchBar)   16  ...      mac     2.5                                                NaN

[167 rows x 15 columns]

In [17]:
df.sort_values(by='price', ascending=False)

         brand                       model  ram  ...       os  weight                                           comments
5        Apple      MacBook Pro (TouchBar)   16  ...      mac     2.5                                                NaN
90   Alienware                 15 Notebook   16  ...  windows     3.5     Maximum Display Resolution : 1920 x 1080 pixel
96   Alienware          AW13R3-7000SLV-PUS    8  ...  windows     2.6  13.3 inch FHD (1920 x 1080) IPS Anti-Glare 300...
31        Acer                 Predator 17   16  ...  windows     4.2                                Integrated Graphics
154  Microsoft      Surface Book CR9-00013    8  ...  windows     1.5                                                NaN
..         ...                         ...  ...  ...      ...     ...                                                ...
73        Acer             Aspire ES1-523     4  ...    linux     2.4                                                NaN
100       Acer    A315-31-P4CRUN.GNTSI.002    4  ...  windows     NaN                                                NaN
108       Acer  Aspire ES-15 NX.GKYSI.010     4  ...  windows     2.4                                                NaN
83        Acer     A315-31CDC UN.GNTSI.001    2  ...  windows     2.1                                                NaN
148       Acer             Aspire SW3-016     2  ...  windows     1.2                                                NaN

[167 rows x 15 columns]

In [18]:
df.sort_values('price')

         brand                       model  ram  ...       os  weight                                           comments
148       Acer             Aspire SW3-016     2  ...  windows     1.2                                                NaN
83        Acer     A315-31CDC UN.GNTSI.001    2  ...  windows     2.1                                                NaN
108       Acer  Aspire ES-15 NX.GKYSI.010     4  ...  windows     2.4                                                NaN
100       Acer    A315-31-P4CRUN.GNTSI.002    4  ...  windows     NaN                                                NaN
73        Acer             Aspire ES1-523     4  ...    linux     2.4                                                NaN
..         ...                         ...  ...  ...      ...     ...                                                ...
154  Microsoft      Surface Book CR9-00013    8  ...  windows     1.5                                                NaN
31        Acer                 Predator 17   16  ...  windows     4.2                                Integrated Graphics
96   Alienware          AW13R3-7000SLV-PUS    8  ...  windows     2.6  13.3 inch FHD (1920 x 1080) IPS Anti-Glare 300...
90   Alienware                 15 Notebook   16  ...  windows     3.5     Maximum Display Resolution : 1920 x 1080 pixel
5        Apple      MacBook Pro (TouchBar)   16  ...      mac     2.5                                                NaN

[167 rows x 15 columns]

In [21]:
df.sort_values(by='price', ascending=False, inplace=True)

In [22]:
df

         brand                       model  ram  ...       os  weight                                           comments
5        Apple      MacBook Pro (TouchBar)   16  ...      mac     2.5                                                NaN
90   Alienware                 15 Notebook   16  ...  windows     3.5     Maximum Display Resolution : 1920 x 1080 pixel
96   Alienware          AW13R3-7000SLV-PUS    8  ...  windows     2.6  13.3 inch FHD (1920 x 1080) IPS Anti-Glare 300...
31        Acer                 Predator 17   16  ...  windows     4.2                                Integrated Graphics
154  Microsoft      Surface Book CR9-00013    8  ...  windows     1.5                                                NaN
..         ...                         ...  ...  ...      ...     ...                                                ...
73        Acer             Aspire ES1-523     4  ...    linux     2.4                                                NaN
100       Acer    A315-31-P4CRUN.GNTSI.002    4  ...  windows     NaN                                                NaN
108       Acer  Aspire ES-15 NX.GKYSI.010     4  ...  windows     2.4                                                NaN
83        Acer     A315-31CDC UN.GNTSI.001    2  ...  windows     2.1                                                NaN
148       Acer             Aspire SW3-016     2  ...  windows     1.2                                                NaN

[167 rows x 15 columns]

In [25]:
df = df.sort_values(by='price', ascending=False)

In [26]:
df

         brand                       model  ram  ...       os  weight                                           comments
5        Apple      MacBook Pro (TouchBar)   16  ...      mac     2.5                                                NaN
90   Alienware                 15 Notebook   16  ...  windows     3.5     Maximum Display Resolution : 1920 x 1080 pixel
96   Alienware          AW13R3-7000SLV-PUS    8  ...  windows     2.6  13.3 inch FHD (1920 x 1080) IPS Anti-Glare 300...
31        Acer                 Predator 17   16  ...  windows     4.2                                Integrated Graphics
154  Microsoft      Surface Book CR9-00013    8  ...  windows     1.5                                                NaN
..         ...                         ...  ...  ...      ...     ...                                                ...
73        Acer             Aspire ES1-523     4  ...    linux     2.4                                                NaN
100       Acer    A315-31-P4CRUN.GNTSI.002    4  ...  windows     NaN                                                NaN
108       Acer  Aspire ES-15 NX.GKYSI.010     4  ...  windows     2.4                                                NaN
83        Acer     A315-31CDC UN.GNTSI.001    2  ...  windows     2.1                                                NaN
148       Acer             Aspire SW3-016     2  ...  windows     1.2                                                NaN

[167 rows x 15 columns]

In [27]:
# 2교시