```python
print('Hello World!')
```

In [2]:
import pandas as pd
df = pd.read_csv('laptops.csv')
df

     brand             model  ram hd_type  hd_size  ...  graphic_card_brand  graphic_card_size       os weight  comments
0     Dell  Inspiron 15-3567    4     hdd     1024  ...               intel                NaN    linux   2.50       NaN
1    Apple       MacBook Air    8     ssd      128  ...               intel                2.0      mac   1.35       NaN
2    Apple       MacBook Air    8     ssd      256  ...               intel                2.0      mac   1.35       NaN
3    Apple       MacBook Pro    8     ssd      128  ...               intel                2.0      mac   3.02       NaN
4    Apple       MacBook Pro    8     ssd      256  ...               intel                2.0      mac   3.02       NaN
..     ...               ...  ...     ...      ...  ...                 ...                ...      ...    ...       ...
162   Asus            A555LF    8     hdd     1024  ...              nvidia                2.0  windows   2.30       NaN
163   Asus     X555LA-XX172D    4     hdd      500  ...               intel                NaN    linux   2.30       NaN
164   Asus            X554LD    2     hdd      500  ...               intel                1.0    linux   2.30       NaN
165   Asus    X550LAV-XX771D    2     hdd      500  ...               intel                NaN    linux   2.50       NaN
166   Asus     X540LA-XX538T    4     hdd     1024  ...               intel                NaN  windows   2.30       NaN

[167 rows x 15 columns]

In [3]:
df.head()

   brand             model  ram hd_type  hd_size  ...  graphic_card_brand  graphic_card_size     os weight  comments
0   Dell  Inspiron 15-3567    4     hdd     1024  ...               intel                NaN  linux   2.50       NaN
1  Apple       MacBook Air    8     ssd      128  ...               intel                2.0    mac   1.35       NaN
2  Apple       MacBook Air    8     ssd      256  ...               intel                2.0    mac   1.35       NaN
3  Apple       MacBook Pro    8     ssd      128  ...               intel                2.0    mac   3.02       NaN
4  Apple       MacBook Pro    8     ssd      256  ...               intel                2.0    mac   3.02       NaN

[5 rows x 15 columns]

In [4]:
df.head(10)

   brand                   model  ram hd_type  ...  graphic_card_size     os  weight             comments
0   Dell        Inspiron 15-3567    4     hdd  ...                NaN  linux    2.50                  NaN
1  Apple             MacBook Air    8     ssd  ...                2.0    mac    1.35                  NaN
2  Apple             MacBook Air    8     ssd  ...                2.0    mac    1.35                  NaN
3  Apple             MacBook Pro    8     ssd  ...                2.0    mac    3.02                  NaN
4  Apple             MacBook Pro    8     ssd  ...                2.0    mac    3.02                  NaN
5  Apple  MacBook Pro (TouchBar)   16     ssd  ...                2.0    mac    2.50                  NaN
6  Apple  MacBook Pro (TouchBar)   16     ssd  ...                2.0    mac    1.37                  NaN
7  Apple                MacBook     8     ssd  ...                2.0    mac    0.92                  NaN
8   Dell             Vostro 3468    4     hdd  ...                NaN  linux    1.76  Integrated Graphics
9   Dell      Inspiron 15.6 3552    4     hdd  ...                NaN  linux    2.19  Integrated Graphics

[10 rows x 15 columns]

In [5]:
df.tail()

    brand           model  ram hd_type  hd_size  ...  graphic_card_brand  graphic_card_size       os weight  comments
162  Asus          A555LF    8     hdd     1024  ...              nvidia                2.0  windows    2.3       NaN
163  Asus   X555LA-XX172D    4     hdd      500  ...               intel                NaN    linux    2.3       NaN
164  Asus          X554LD    2     hdd      500  ...               intel                1.0    linux    2.3       NaN
165  Asus  X550LAV-XX771D    2     hdd      500  ...               intel                NaN    linux    2.5       NaN
166  Asus   X540LA-XX538T    4     hdd     1024  ...               intel                NaN  windows    2.3       NaN

[5 rows x 15 columns]

In [6]:
df.tail(10)

      brand                          model  ram  ...       os  weight                                      comments
157  Lenovo  IdeaPad 520-15IKB 80YL00RXIN     8  ...  windows    2.20  Core i7-7500U 7th Gen processor, Dolby Audio
158    Asus                  X540YA-XO290D    4  ...    linux    2.00                                           NaN
159    Asus                        P2420SA    4  ...    linux    1.95                                           NaN
160    Asus                  X540LA-XX596D    4  ...    linux    1.90                                           NaN
161    Asus                 X541UA-GO1345D    4  ...    linux    1.84                                           NaN
162    Asus                         A555LF    8  ...  windows    2.30                                           NaN
163    Asus                  X555LA-XX172D    4  ...    linux    2.30                                           NaN
164    Asus                         X554LD    2  ...    linux    2.30                                           NaN
165    Asus                 X550LAV-XX771D    2  ...    linux    2.50                                           NaN
166    Asus                  X540LA-XX538T    4  ...  windows    2.30                                           NaN

[10 rows x 15 columns]

In [7]:
df.shape

(167, 15)

In [8]:
df.shape[0]

167

In [9]:
df.shape[1]

15

In [10]:
df.index

RangeIndex(start=0, stop=167, step=1)

In [11]:
df.columns

Index(['brand', 'model', 'ram', 'hd_type', 'hd_size', 'screen_size', 'price',
       'processor_brand', 'processor_model', 'clock_speed',
       'graphic_card_brand', 'graphic_card_size', 'os', 'weight', 'comments'],
      dtype='object')

In [12]:
df.columns[0]

'brand'

In [13]:
df.columns[1]

'model'

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167 entries, 0 to 166
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   brand               167 non-null    object
 1   model               167 non-null    object
 2   ram                 167 non-null    int64
 3   hd_type             167 non-null    object
 4   hd_size             167 non-null    int64
 5   screen_size         167 non-null    float64
 6   price               167 non-null    int64
 7   processor_brand     167 non-null    object
 8   processor_model     167 non-null    object
 9   clock_speed         166 non-null    float64
 10  graphic_card_brand  163 non-null    object
 11  graphic_card_size   81 non-null     float64
 12  os                  167 non-null    object
 13  weight              160 non-null    float64
 14  comments            55 non-null     object
dtypes: float64(4), int64(3), object(8)
memory usage: 19.7+ KB

In [15]:
df.describe()

              ram     hd_size  screen_size          price  clock_speed  graphic_card_size      weight
count  167.000000   167.00000   167.000000     167.000000   166.000000          81.000000  160.000000
mean     6.898204   768.91018    14.775210   64132.898204     2.321084          52.160494    2.250813
std      3.787479   392.99080     1.376526   42797.674010     0.554187         444.134142    0.648446
min      2.000000    32.00000    10.100000   13872.000000     1.100000           1.000000    0.780000
25%      4.000000   500.00000    14.000000   35457.500000     1.900000           2.000000    1.900000
50%      8.000000  1024.00000    15.600000   47990.000000     2.300000           2.000000    2.200000
75%      8.000000  1024.00000    15.600000   77494.500000     2.600000           4.000000    2.600000
max     16.000000  2048.00000    17.600000  226000.000000     3.800000        4000.000000    4.200000

In [16]:
df.sort_values(by='price')

         brand                       model  ram  ...       os  weight                                           comments
148       Acer             Aspire SW3-016     2  ...  windows     1.2                                                NaN
83        Acer     A315-31CDC UN.GNTSI.001    2  ...  windows     2.1                                                NaN
108       Acer  Aspire ES-15 NX.GKYSI.010     4  ...  windows     2.4                                                NaN
100       Acer    A315-31-P4CRUN.GNTSI.002    4  ...  windows     NaN                                                NaN
73        Acer             Aspire ES1-523     4  ...    linux     2.4                                                NaN
..         ...                         ...  ...  ...      ...     ...                                                ...
154  Microsoft      Surface Book CR9-00013    8  ...  windows     1.5                                                NaN
31        Acer                 Predator 17   16  ...  windows     4.2                                Integrated Graphics
96   Alienware          AW13R3-7000SLV-PUS    8  ...  windows     2.6  13.3 inch FHD (1920 x 1080) IPS Anti-Glare 300...
90   Alienware                 15 Notebook   16  ...  windows     3.5     Maximum Display Resolution : 1920 x 1080 pixel
5        Apple      MacBook Pro (TouchBar)   16  ...      mac     2.5                                                NaN

[167 rows x 15 columns]

In [17]:
df.sort_values(by='price', ascending=False)

         brand                       model  ram  ...       os  weight                                           comments
5        Apple      MacBook Pro (TouchBar)   16  ...      mac     2.5                                                NaN
90   Alienware                 15 Notebook   16  ...  windows     3.5     Maximum Display Resolution : 1920 x 1080 pixel
96   Alienware          AW13R3-7000SLV-PUS    8  ...  windows     2.6  13.3 inch FHD (1920 x 1080) IPS Anti-Glare 300...
31        Acer                 Predator 17   16  ...  windows     4.2                                Integrated Graphics
154  Microsoft      Surface Book CR9-00013    8  ...  windows     1.5                                                NaN
..         ...                         ...  ...  ...      ...     ...                                                ...
73        Acer             Aspire ES1-523     4  ...    linux     2.4                                                NaN
100       Acer    A315-31-P4CRUN.GNTSI.002    4  ...  windows     NaN                                                NaN
108       Acer  Aspire ES-15 NX.GKYSI.010     4  ...  windows     2.4                                                NaN
83        Acer     A315-31CDC UN.GNTSI.001    2  ...  windows     2.1                                                NaN
148       Acer             Aspire SW3-016     2  ...  windows     1.2                                                NaN

[167 rows x 15 columns]

In [18]:
df.sort_values('price')

         brand                       model  ram  ...       os  weight                                           comments
148       Acer             Aspire SW3-016     2  ...  windows     1.2                                                NaN
83        Acer     A315-31CDC UN.GNTSI.001    2  ...  windows     2.1                                                NaN
108       Acer  Aspire ES-15 NX.GKYSI.010     4  ...  windows     2.4                                                NaN
100       Acer    A315-31-P4CRUN.GNTSI.002    4  ...  windows     NaN                                                NaN
73        Acer             Aspire ES1-523     4  ...    linux     2.4                                                NaN
..         ...                         ...  ...  ...      ...     ...                                                ...
154  Microsoft      Surface Book CR9-00013    8  ...  windows     1.5                                                NaN
31        Acer                 Predator 17   16  ...  windows     4.2                                Integrated Graphics
96   Alienware          AW13R3-7000SLV-PUS    8  ...  windows     2.6  13.3 inch FHD (1920 x 1080) IPS Anti-Glare 300...
90   Alienware                 15 Notebook   16  ...  windows     3.5     Maximum Display Resolution : 1920 x 1080 pixel
5        Apple      MacBook Pro (TouchBar)   16  ...      mac     2.5                                                NaN

[167 rows x 15 columns]

In [21]:
df.sort_values(by='price', ascending=False, inplace=True)

In [22]:
df

         brand                       model  ram  ...       os  weight                                           comments
5        Apple      MacBook Pro (TouchBar)   16  ...      mac     2.5                                                NaN
90   Alienware                 15 Notebook   16  ...  windows     3.5     Maximum Display Resolution : 1920 x 1080 pixel
96   Alienware          AW13R3-7000SLV-PUS    8  ...  windows     2.6  13.3 inch FHD (1920 x 1080) IPS Anti-Glare 300...
31        Acer                 Predator 17   16  ...  windows     4.2                                Integrated Graphics
154  Microsoft      Surface Book CR9-00013    8  ...  windows     1.5                                                NaN
..         ...                         ...  ...  ...      ...     ...                                                ...
73        Acer             Aspire ES1-523     4  ...    linux     2.4                                                NaN
100       Acer    A315-31-P4CRUN.GNTSI.002    4  ...  windows     NaN                                                NaN
108       Acer  Aspire ES-15 NX.GKYSI.010     4  ...  windows     2.4                                                NaN
83        Acer     A315-31CDC UN.GNTSI.001    2  ...  windows     2.1                                                NaN
148       Acer             Aspire SW3-016     2  ...  windows     1.2                                                NaN

[167 rows x 15 columns]

In [25]:
df = df.sort_values(by='price', ascending=False)

In [26]:
df

         brand                       model  ram  ...       os  weight                                           comments
5        Apple      MacBook Pro (TouchBar)   16  ...      mac     2.5                                                NaN
90   Alienware                 15 Notebook   16  ...  windows     3.5     Maximum Display Resolution : 1920 x 1080 pixel
96   Alienware          AW13R3-7000SLV-PUS    8  ...  windows     2.6  13.3 inch FHD (1920 x 1080) IPS Anti-Glare 300...
31        Acer                 Predator 17   16  ...  windows     4.2                                Integrated Graphics
154  Microsoft      Surface Book CR9-00013    8  ...  windows     1.5                                                NaN
..         ...                         ...  ...  ...      ...     ...                                                ...
73        Acer             Aspire ES1-523     4  ...    linux     2.4                                                NaN
100       Acer    A315-31-P4CRUN.GNTSI.002    4  ...  windows     NaN                                                NaN
108       Acer  Aspire ES-15 NX.GKYSI.010     4  ...  windows     2.4                                                NaN
83        Acer     A315-31CDC UN.GNTSI.001    2  ...  windows     2.1                                                NaN
148       Acer             Aspire SW3-016     2  ...  windows     1.2                                                NaN

[167 rows x 15 columns]

In [27]:
# 2교시

In [28]:
import pandas as pd
df = pd.read_csv('laptops.csv')
df

     brand             model  ram hd_type  hd_size  ...  graphic_card_brand  graphic_card_size       os weight  comments
0     Dell  Inspiron 15-3567    4     hdd     1024  ...               intel                NaN    linux   2.50       NaN
1    Apple       MacBook Air    8     ssd      128  ...               intel                2.0      mac   1.35       NaN
2    Apple       MacBook Air    8     ssd      256  ...               intel                2.0      mac   1.35       NaN
3    Apple       MacBook Pro    8     ssd      128  ...               intel                2.0      mac   3.02       NaN
4    Apple       MacBook Pro    8     ssd      256  ...               intel                2.0      mac   3.02       NaN
..     ...               ...  ...     ...      ...  ...                 ...                ...      ...    ...       ...
162   Asus            A555LF    8     hdd     1024  ...              nvidia                2.0  windows   2.30       NaN
163   Asus     X555LA-XX172D    4     hdd      500  ...               intel                NaN    linux   2.30       NaN
164   Asus            X554LD    2     hdd      500  ...               intel                1.0    linux   2.30       NaN
165   Asus    X550LAV-XX771D    2     hdd      500  ...               intel                NaN    linux   2.50       NaN
166   Asus     X540LA-XX538T    4     hdd     1024  ...               intel                NaN  windows   2.30       NaN

[167 rows x 15 columns]

In [30]:
df['brand']

0       Dell
1      Apple
2      Apple
3      Apple
4      Apple
       ...
162     Asus
163     Asus
164     Asus
165     Asus
166     Asus
Name: brand, Length: 167, dtype: object

In [32]:
df['brand'].unique()

array(['Dell', 'Apple', 'Acer', 'HP', 'Lenovo', 'Alienware', 'Microsoft',
       'Asus'], dtype=object)

In [37]:
df['brand'].value_counts()

brand
HP           55
Acer         35
Dell         31
Lenovo       18
Asus          9
Apple         7
Alienware     6
Microsoft     6
Name: count, dtype: int64

In [36]:
df['brand'].describe()

count     167
unique      8
top        HP
freq       55
Name: brand, dtype: object

In [38]:
df['brand'].describe()[1]

C:\Users\Administrator\AppData\Local\Temp\ipykernel_10916\2607132936.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['brand'].describe()[1]

8

In [39]:
df['brand'].describe()[2]

C:\Users\Administrator\AppData\Local\Temp\ipykernel_10916\2763937768.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['brand'].describe()[2]

'HP'

In [40]:
df['brand'].describe()[3]

C:\Users\Administrator\AppData\Local\Temp\ipykernel_10916\251240141.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['brand'].describe()[3]

55

In [41]:
df['price'].max()

226000

In [42]:
df['price'].min()

13872

In [43]:
df['price'].mean()

64132.89820359281

In [44]:
df['price'].std()

42797.67400962525

In [45]:
df['price'].count()

167

In [46]:
df['ram']

0      4
1      8
2      8
3      8
4      8
      ..
162    8
163    4
164    2
165    2
166    4
Name: ram, Length: 167, dtype: int64

In [47]:
df['ram'].value_counts()

ram
8     69
4     68
16    17
2     10
12     3
Name: count, dtype: int64

In [49]:
df['graphic_card_brand']

0       intel
1       intel
2       intel
3       intel
4       intel
        ...
162    nvidia
163     intel
164     intel
165     intel
166     intel
Name: graphic_card_brand, Length: 167, dtype: object

In [50]:
df['graphic_card_brand'].value_counts()

graphic_card_brand
intel     77
nvidia    49
amd       37
Name: count, dtype: int64

In [56]:
df['hd_type']

0      hdd
1      ssd
2      ssd
3      ssd
4      ssd
      ...
162    hdd
163    hdd
164    hdd
165    hdd
166    hdd
Name: hd_type, Length: 167, dtype: object

In [57]:
df['processor_model']

0              i5
1              i5
2              i5
3              i5
4              i5
          ...
162    i3 4th gen
163    i3 4th gen
164    i3 4th gen
165    i3 4th gen
166    i3 5th gen
Name: processor_model, Length: 167, dtype: object

In [58]:
df['hd_type'].value_counts()

hd_type
hdd    121
ssd     46
Name: count, dtype: int64

In [59]:
df['processor_model'].value_counts()

processor_model
i5                   70
i7                   32
i3                   29
i3 4th gen            4
Pentium N3710         2
i3 5th gen            2
A4-7210               2
i3                    2
pentium N3710         1
i3 6th gen            1
Pentium Quad Core     1
APU Quad Core E2      1
Atom Z8300            1
E1-7010               1
E1-6015               1
A6-7310               1
Celeron N3060         1
Pentium N3710         1
I3                    1
APU Dual Core A4      1
Pentium N3825U        1
core m                1
E2-7110               1
Pentium N3700         1
pentium               1
Celeron               1
Pentium 3805U         1
A10-8700P             1
FX 9830P              1
E2                    1
Celeron 3855U         1
Pentium               1
Name: count, dtype: int64

In [61]:
df['hd_type'].value_counts() & df['processor_model'].value_counts()

C:\Users\Administrator\AppData\Local\Temp\ipykernel_10916\1082047236.py:1: FutureWarning: Operation between non boolean Series with different indexes will no longer return a boolean result in a future version. Cast both Series to object type to maintain the prior behavior.
  df['hd_type'].value_counts() & df['processor_model'].value_counts()

A10-8700P            False
A4-7210              False
A6-7310              False
APU Dual Core A4     False
APU Quad Core E2     False
Atom Z8300           False
Celeron              False
Celeron 3855U        False
Celeron N3060        False
E1-6015              False
E1-7010              False
E2                   False
E2-7110              False
FX 9830P             False
I3                   False
Pentium              False
Pentium 3805U        False
Pentium N3700        False
Pentium N3710        False
Pentium N3710        False
Pentium N3825U       False
Pentium Quad Core    False
core m               False
hdd                  False
i3                   False
i3                   False
i3 4th gen           False
i3 5th gen           False
i3 6th gen           False
i5                   False
i7                   False
pentium              False
pentium N3710        False
ssd                  False
Name: count, dtype: bool

In [63]:
df[['hd_type'],['processor_model']].value_counts()

InvalidIndexError: (['hd_type'], ['processor_model'])

In [65]:
df['processor_brand'] == 'i5'

0      False
1      False
2      False
3      False
4      False
       ...
162    False
163    False
164    False
165    False
166    False
Name: processor_brand, Length: 167, dtype: bool

In [67]:
df['processor_model'] == 'i5'

0       True
1       True
2       True
3       True
4       True
       ...
162    False
163    False
164    False
165    False
166    False
Name: processor_model, Length: 167, dtype: bool

In [66]:
df['hd_type'] == 'ssd'

0      False
1       True
2       True
3       True
4       True
       ...
162    False
163    False
164    False
165    False
166    False
Name: hd_type, Length: 167, dtype: bool

In [69]:
((df['processor_model'] == 'i5') &  (df['hd_type'] == 'ssd')).value_counts()

False    149
True      18
Name: count, dtype: int64

In [70]:
df.sort_values('price', ascending=False).head(10)

         brand                     model  ram  ...       os  weight                                           comments
5        Apple    MacBook Pro (TouchBar)   16  ...      mac    2.50                                                NaN
90   Alienware               15 Notebook   16  ...  windows    3.50     Maximum Display Resolution : 1920 x 1080 pixel
96   Alienware        AW13R3-7000SLV-PUS    8  ...  windows    2.60  13.3 inch FHD (1920 x 1080) IPS Anti-Glare 300...
31        Acer               Predator 17   16  ...  windows    4.20                                Integrated Graphics
154  Microsoft    Surface Book CR9-00013    8  ...  windows    1.50                                                NaN
122  Alienware             ANW17-2143SLV    8  ...  windows    3.80  17.3 inch FHD (1920 x 1080) IPS-Panel Anti-Gla...
151  Microsoft  Surface Laptop DAG-00001    8  ...  windows    1.20                                Integrated Graphics
34          HP              Omen W 250TX   16  ...  windows    2.70  The Best Gaming is on GeForce Discover desktop...
44          HP                13-ac059TU   16  ...  windows     NaN                                                NaN
6        Apple    MacBook Pro (TouchBar)   16  ...      mac    1.37                                                NaN

[10 rows x 15 columns]

In [72]:
df['os'] == 'mac'

0      False
1       True
2       True
3       True
4       True
       ...
162    False
163    False
164    False
165    False
166    False
Name: os, Length: 167, dtype: bool

In [73]:
df['clock_speed'] == 2.9

0      False
1      False
2      False
3      False
4      False
       ...
162    False
163    False
164    False
165    False
166    False
Name: clock_speed, Length: 167, dtype: bool

In [80]:
df.loc[(df['os'] == 'mac') & (df['clock_speed'] == 2.9), ['model', 'price']]

                    model   price
6  MacBook Pro (TouchBar)  158000

## **2026년 5월 27일 수요일**

In [1]:
import pandas as pd
iphone_df = pd.read_csv('iphone.csv')
iphone_df

      Unnamed: 0         출시일  디스플레이  메모리     출시 버전 Face ID
0       iPhone 7  2016-09-16    4.7  2GB  iOS 10.0      No
1  iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
2       iPhone 8  2017-09-22    4.7  2GB  iOS 11.0      No
3  iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
4       iPhone X  2017-11-03    5.8  3GB  iOS 11.1     Yes
5      iPhone XS  2018-09-21    5.8  4GB  iOS 12.0     Yes
6  iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [2]:
True, False

(True, False)

In [3]:
Why

NameError: name 'Why' is not defined