## 데이터 분석을 위한 라이브러리, 판다스를 가져온다.

In [1]:
import pandas as pd

## 이어서 해본다... **Dataframe**을 만들어보고 실습해보자.

In [2]:
two_dimensional_list = [['dongwook',50,86],['sineui',89,31],['ikjoong',68,91],['yoonsoo',88,75]]

In [3]:
# 이제 데이터 프레임이 출력될까?
my_df = pd.DataFrame(two_dimensional_list)
my_df

          0   1   2
0  dongwook  50  86
1    sineui  89  31
2   ikjoong  68  91
3   yoonsoo  88  75

## **20260318wed_start**

In [5]:
two_dimensional_list # 간단히 Raw 상태를 보기

[['dongwook', 50, 86],
 ['sineui', 89, 31],
 ['ikjoong', 68, 91],
 ['yoonsoo', 88, 75]]

In [6]:
my_df = pd.DataFrame(two_dimensional_list) # my_df 변수에 앞서서 한거 넣기. 데이터 프레임으로 보기 위함.
my_df

          0   1   2
0  dongwook  50  86
1    sineui  89  31
2   ikjoong  68  91
3   yoonsoo  88  75

### 위는 4행 3열이다.

In [8]:
type(two_dimensional_list)

list

### 자료형은 리스트다.

In [9]:
type(my_df)

pandas.core.frame.DataFrame

### 판다스 코어라는 것을 보여준다...

행 번호 = INDEX

In [13]:
my_df = pd.DataFrame(two_dimensional_list, columns=['name','english_score','math_score'])
my_df

       name  english_score  math_score
0  dongwook             50          86
1    sineui             89          31
2   ikjoong             68          91
3   yoonsoo             88          75

#### 반드시 데이터 프레임의 **컬럼을 다 넣어야** 한다. 컬럼 제목을 직접 정의한다.

In [15]:
my_df = pd.DataFrame(two_dimensional_list, columns=['name','english_score','math_score'], index=['a','b','c','d'])
my_df

       name  english_score  math_score
a  dongwook             50          86
b    sineui             89          31
c   ikjoong             68          91
d   yoonsoo             88          75

#### **인덱스 제목도 정의했다.**

In [17]:
my_df.columns

Index(['name', 'english_score', 'math_score'], dtype='object')

### my_df의 컬럼들을 다 볼수 있는 코드(구문)이다.

In [18]:
my_df.index

Index(['a', 'b', 'c', 'd'], dtype='object')

### my_df의 인덱스들을 다 볼수 있는 코드(구문)이다.

In [21]:
my_df.dtypes

name             object
english_score     int64
math_score        int64
dtype: object

### **자료형**들이 뭔지 살펴보기