In [1]:
import pandas as pd
df =pd.read_csv('health1.csv', index_col=0)
df

    Gender  Height (Inch)  Weight (Pound)
ID
0      NaN      73.847017      241.893563
1      NaN      70.000000      200.000000
2      NaN      74.110105      212.740856
3      NaN      71.730978      220.042470
4      NaN      69.881796      206.349801
5      NaN      67.253016      152.212156
6      NaN      68.785081      183.927889
7      NaN      68.348516      167.971111
8      NaN      67.018950      175.929440
9      NaN      63.456494      156.399676
10     NaN      71.195382      186.604926
11     NaN      62.636675      102.853563
12     NaN      62.077832      138.691680
13     NaN      60.030434       97.687432
14     NaN      59.098250      110.529686
15     NaN      66.172652      136.777454
16     NaN      67.067155      170.867906
17     NaN      63.867992      128.475319
18     NaN      69.034243      163.852461
19     NaN      61.944246      113.649103
20     NaN      70.000000      200.000000

In [ ]:
df.('Gender' = Male)

```python
df.('Gender' = Male)
# Sleepy
```

```python
# Try
```

In [6]:
df.[('비만도') = ('정상'), inplace=True]

SyntaxError: invalid syntax (1066270162.py, line 1)

In [7]:
df['비만도'] = '정상'
df

    Gender  Height (Inch)  Weight (Pound) 비만도
ID
0      NaN      73.847017      241.893563  정상
1      NaN      70.000000      200.000000  정상
2      NaN      74.110105      212.740856  정상
3      NaN      71.730978      220.042470  정상
4      NaN      69.881796      206.349801  정상
5      NaN      67.253016      152.212156  정상
6      NaN      68.785081      183.927889  정상
7      NaN      68.348516      167.971111  정상
8      NaN      67.018950      175.929440  정상
9      NaN      63.456494      156.399676  정상
10     NaN      71.195382      186.604926  정상
11     NaN      62.636675      102.853563  정상
12     NaN      62.077832      138.691680  정상
13     NaN      60.030434       97.687432  정상
14     NaN      59.098250      110.529686  정상
15     NaN      66.172652      136.777454  정상
16     NaN      67.067155      170.867906  정상
17     NaN      63.867992      128.475319  정상
18     NaN      69.034243      163.852461  정상
19     NaN      61.944246      113.649103  정상
20     NaN      70.000000      200.000000  정상

In [9]:
df.loc[0:10,'Gender'] = 'Male'
df.loc[11:20,'Gender'] = 'Female'
df

    Gender  Height (Inch)  Weight (Pound) 비만도
ID
0     Male      73.847017      241.893563  정상
1     Male      70.000000      200.000000  정상
2     Male      74.110105      212.740856  정상
3     Male      71.730978      220.042470  정상
4     Male      69.881796      206.349801  정상
5     Male      67.253016      152.212156  정상
6     Male      68.785081      183.927889  정상
7     Male      68.348516      167.971111  정상
8     Male      67.018950      175.929440  정상
9     Male      63.456494      156.399676  정상
10    Male      71.195382      186.604926  정상
11  Female      62.636675      102.853563  정상
12  Female      62.077832      138.691680  정상
13  Female      60.030434       97.687432  정상
14  Female      59.098250      110.529686  정상
15  Female      66.172652      136.777454  정상
16  Female      67.067155      170.867906  정상
17  Female      63.867992      128.475319  정상
18  Female      69.034243      163.852461  정상
19  Female      61.944246      113.649103  정상
20  Female      70.000000      200.000000  정상